package task3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class Use_junit {
private WebDriver driver;
private Map<String, Object> vars;
        JavascriptExecutor js;
@Before
public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        }
@After
public void tearDown() {
        driver.quit();
        }
@Test
public void Use_junit() {
        driver.get("https://ru-ru.facebook.com//v3/signin/identifier?dsh=S-1391977685%3A1687969519465794&continue=https%3A%2F%2Faccounts.google.com%2F&followup=https%3A%2F%2Faccounts.google.com%2F&ifkv=Af_xneGkKyWS3WL_CqAlZV8u-1pta5bOFhpD7fEsFvPMtD-8EXwrNaolovB5ACfObkIkMItn0oBeCA&passive=1209600&flowName=GlifWebSignIn&flowEntry=ServiceLogin");
        driver.manage().window().setSize(new Dimension(550, 689));
        driver.findElement(By.id("identifierId")).sendKeys("sanya.gubanova.02@gmail.com");
        driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click();
        {
        WebElement element = driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
        }
        {
        WebElement element = driver.findElement(By.tagName("body"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.name("Passwd")).sendKeys("alya2002");
        driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click();
        {
        WebElement element = driver.findElement(By.cssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
        }
        }
        }
